spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: /Users/choehojun/Documents/imageTest/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  #  ssl:
  #    enabled: true
  #    key-store: keystore.p12
  #    key-store-password: P@ssw0rd
  #  port: 443
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled : true
    path: /error
    include-message: always
active:
  server: local
  max-http-header-size: 0

post-file:
  path: /Users/choehojun/Documents/imageTest/